#!/bin/bash

if [ "$DOCKER_CONTAINER" = "1" ]; then
    export MYSQL_PWD="$MYSQL_ROOT_PASSWORD"
    MYSQL_CMD="mysql -u root -h localhost"
else
    MYSQL_CMD="sudo MYSQL_DATABASE=\"$MYSQL_DATABASE\" MYSQL_USERNAME=\"$MYSQL_USERNAME\" MYSQL_PASSWORD=\"$MYSQL_PASSWORD\" mysql -u root"
fi

$MYSQL_CMD <<-EOSQL
    DROP USER IF EXISTS '$MYSQL_USERNAME'@'%';
    DROP USER IF EXISTS '$MYSQL_USERNAME'@'localhost';
    DROP DATABASE IF EXISTS $MYSQL_DATABASE;

    CREATE DATABASE $MYSQL_DATABASE;

    CREATE USER IF NOT EXISTS '$MYSQL_USERNAME'@'%' IDENTIFIED WITH mysql_native_password BY '$MYSQL_PASSWORD';
    GRANT SELECT ON $MYSQL_DATABASE.* TO '$MYSQL_USERNAME'@'%';
    FLUSH PRIVILEGES;

    USE $MYSQL_DATABASE;

    source app/db/schema.sql;
EOSQL
