source ./.env

export MYSQL_PASSWORD=$MYSQL_PASSWORD
export MYSQL_USERNAME=$MYSQL_USERNAME
export MYSQL_DATABASE=$MYSQL_DATABASE
export MYSQL_PORT=$MYSQL_PORT
export MYSQL_HOST=$MYSQL_HOST

./app/db/setup.sh
